Updated the general style of the style guide to make it more readable
prolificinteractive/swift-style-guide pull request #46
Opened 2016-11-21 17:45 UTC by ThibaultKlein

@htinlinn @paulmiard

2016-11-28 17:27 UTC, htinlinn requested changes
Can we also do a quick search for "Rationale" and make sure that they all have colons after them? Right now, some of them do and some of them don't.

2016-11-28 17:27 UTC, htinlinn commented on README.md
> +# Overview #
Let's get rid of the trailing # from this line as well.

2016-11-28 17:27 UTC, htinlinn commented on README.md
> +# Standards #
Here too.

2016-11-28 17:27 UTC, htinlinn commented on README.md
> +## Naming Conventions ##
And here.

2017-01-23 17:37 UTC, htinlinn approved these changes

2017-01-23 17:45 UTC, paulmiard commented
Looks good, let's also update the best practices section?

2017-01-23 18:00 UTC, htinlinn commented on BestPractices.md
> +# BEST PRACTICES
Make this "Best Practices"

2017-01-23 18:11 UTC, htinlinn requested changes

2017-01-23 18:11 UTC, htinlinn commented on BestPractices.md
> +## Table Of Contents
Table Of Contents uses header level 1, not 2 in the main file. Maybe we change this to `#` and also bump everything else up.

2017-01-23 18:11 UTC, htinlinn commented on BestPractices.md
>  Although crashing on production is not always the ideal. Often you prefer crashing on debug but in production handle the error with a default value like 0 or empty array. To do so, we recommand imple
Replace the first two sentences with the following.

```
While forcing a crash in debug builds is acceptable for testing purposes, it is not ideal to have the program exit on assertion failure in production builds. Instead, handling the error with a default value like `0` or empty array might be preferable. 
```

2017-01-23 18:11 UTC, htinlinn commented on BestPractices.md
> -#### Production ####
Change this to "Production Builds".

2017-01-23 18:11 UTC, htinlinn commented on BestPractices.md
> +##### Example
Make sure that the subsections here the same number of `#` as subsections in the other sections.

2017-02-13 19:58 UTC, htinlinn approved these changes

2017-04-25 21:14 UTC, phillfarrugia approved these changes

2017-04-25 21:24 UTC, paulmiard commented
👍

2017-04-25 21:31 UTC, merged